use_sp_pts: true
topk_clip: 6
topk: 3
vlm_score_thr: 6
vlm_provider: 'vllm'
vlm_model: 'Qwen/Qwen3-VL-30B-A3B-Thinking'
vlm_name: qwen3_vl_30b_thinking
vlm_parallel_queries: 48
seg_model: sam3
clip_params:
  model_name: 'PE-Core-bigG-14-448'
  pretrained: 'meta'
  clip_bs: 32
log_params:
  log_dir: "./logs"
  print_freq: 100
eval_params:
  num_images: 300
  full_eval: true
  num_samples: 500
paths:
  root_path: ./data/scannet
  ann_path: ./data/nr3d/nr3d_ann.json
  pkl_path: ./data/scannet/scannet_oof_infos_val.pkl
  sam3_root: "./sam3"
  sam3_model_path: "./sam3/pretrained/sam3.pt"
  output_agent_dir: 'agent_outputs_nr3d_qwen30b'